language: node_js
sudo: required
services:
    - docker

before_install:
    - docker build -t prabjyot29/docker-practise -f Dockerfile.dev .

script:
    - docker run -e CI=true prabjyot29/docker-practise npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-practise"
    env: "DockerPractise-env"
    bucket_name: "elasticbeanstalk-ap-south-1-424447673730"
    bucket_path: "docker-practise"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
