sudo: required
services:
    - docker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-practise"
    env: "DockerPractise-env"
    bucket_name: "elasticbeanstalk-ap-south-1-424447673730"
    bucket_path: "docker-practise"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
